import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import { allCodes } from '~/allCodes'
import CardTransitions from '~/components/CardTransitions/CardTransitions'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Threat Modeling Playing Cards',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <CardTransitions codes={allCodes} />
      </head>
      <body className={inter.className}>
        <div className="min-h-screen">
          <div className="antialiased bg-gray-100">
            <div className="w-full text-gray-700 bg-white">
              <div className="flex flex-col px-4 mx-auto md:items-center md:justify-between md:flex-row md:px-6 lg:px-8">
                <div className="flex flex-row items-center justify-between p-4">
                  <Link href="/" className="text-lg font-semibold tracking-widest text-gray-900 uppercase rounded-lg focus:outline-none focus:shadow-outline">
                    Threat Modeling
                  </Link>
                </div>
              </div>
            </div>
          </div>

          {children}
        </div>
      </body >
    </html >
  )
}
